// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectApp() (*app, func(), error) {
	flags, err := newFlags()
	if err != nil {
		return nil, nil, err
	}
	config, err := newConfig(flags)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := newLogger(config)
	if err != nil {
		return nil, nil, err
	}
	clientApp, err := newCLI(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApp := newApp(clientApp, flags)
	return mainApp, func() {
		cleanup()
	}, nil
}
